include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    omit_local_variable_types: false

analyzer:
  errors:
    todo: ignore
  exclude:
    - "**.g.dart"
