name: client_data
description: "A new Flutter package project."
version: 0.0.1
homepage: null
publish_to: none

environment:
  sdk: '>=3.2.0-220.0.dev <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.13.5
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  http: ^1.1.0
  json_annotation: ^4.8.1
  matcher: ^0.12.16
  platform: ^3.1.3
  shared_data:
    path: ../shared_data

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.3
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  mocktail: ^1.0.1
  very_good_analysis: ^5.1.0
